### ISSUE TITLE
Debate whether a monorepo would be an option

### ISSUE THREAD

**Issue by JosXa** [python-telegram-bot/ptbcontrib#2]
Before we commit completely on the repo architecture, I just wanted to throw the idea of using a monorepo tool in the room one more time.
I am by no means an expert on it, but from what I know the concept really fits.

See here for some inspiration:
- https://github.com/korfuri/awesome-monorepo
- https://www.reddit.com/r/Python/comments/boi3es/created_a_python_monorepo_with_version_release/?utm_medium=android_app&utm_source=share

Concrete tools and examples for Python:
- https://pypi.org/project/scream/
- https://github.com/ya-mori/python-monorepo
- https://github.com/Parquery/pypackagery

**Comment by Bibo-Joshi** [comment]
From what I understand, a monorepo is just a different philosophy on how to set up a repo containing multiple libraries/package/parts of code that are usually dependent on each other, right? I don't think I see a big advantage of that. Like the main problem of having everything in one repo, namely what I mentioned [here](https://github.com/python-telegram-bot/python-telegram-bot/issues/1912#issuecomment-710113161) can not resolved by that. On the other hand, there are some downsides regarding maintainability. Citing this [article](https://medium.com/opendoor-labs/our-python-monorepo-d34028f2b6fa):

> * Some other opensource tools aren’t adapted well to monorepos. E.g., linters are intended to be run on one project, in one virtual environment, at a time. If you try to run, say, pylint project1 project2, where those each have their own virtual envs, it won’t work correctly. Hence we had to write tooling around many of these tools to make sure tools always work as expected.
> * Likewise, many CI/CD systems aren’t setup to handle monorepos, so you’ll need to invest in some tooling to get it working. Similarly, to build Dockerfiles optimized for layer caching, we needed extra tooling. So basically, if you have a monorepo, expect to invest in tooling around it.

As the individual module of `ptbcontrib` should be independent of each other anyway (I don't think allowing contributions to rely on other contributions is a good idea, they should just enhance the existing one), I don't see the selling point of a monorepo in our case.
But maybe that's just me, so please elaborate if you think I'm wrong :)

**Comment by JosXa** [comment]
No, sounds alright to me and you've clearly given it more thought!

I'd say leave this open for a week and see if someone else has an opinion, then if not we're good
