### ISSUE TITLE
[FEATURE] Forward message as copy

### ISSUE THREAD

**Issue by moonbaseDelta** [python-telegram-bot/ptbcontrib#3]
Hello again! 
In Pyrogram there's a nice feature that helps with some tasks like editing posts before publications:
https://docs.pyrogram.org/api/bound-methods/Message.forward
https://github.com/pyrogram/pyrogram/blob/develop/pyrogram/client/methods/messages/forward_messages.py

It just get the whole message and resends it as if it's written by bot, without a forwarding header.I have a solution in rather ugly manner, but it's not good with photo albums (many pics with caption viewed as single message in the client) cause it force 'em to be send as many single photo-messages not a whole one.

```
 
    def determine_msg_type_then_send( ... , msg, ... ): 
        if msg.photo:   
            ...
            send_a_photo_function( <someargs> ) 
        elif msg.document:  
            ...
            send_a_document_function( <someargs> ) 
        elif msg.sticker:  
            ...
            send_a_sticker_function( <someargs> )  
        ...
        else:  
            ... 
            send_a_message_function( <someargs> ) 
 

```

**Comment by PaarthShah** [comment]
Would such functionality, in the planned implementation, also automatically work for forwarding picture/video/etc messages? That's my real usecase anyway.

**Comment by Bibo-Joshi** [comment]
> Would such functionality, in the planned implementation, also automatically work for forwarding picture/video/etc messages? That's my real usecase anyway.

yes, that would be the idea. ideally, it would also handle media groups properly and maybe allow customization of captions or adding a custom header to the existing caption/text. but that's upt to whoever goes for implementing this.

**Comment by Poolitzer** [comment]
I actually did something more or less exactly like this a couple of weeks ago: https://github.com/Poolitzer/channelforwarder/blob/master/main.py. Someone would only need to alter it slightly and probably document/comment on the code itself.

**Comment by Bibo-Joshi** [comment]
will be redundant, once Bot API 5.0 is available through PTB. closing.
