### ISSUE TITLE
How can I get Tg user's phone number by just knowing his/her Telegram ID? 

### ISSUE THREAD

**Issue by abarreto250** [python-telegram-bot/ptbcontrib#38]
Hi everyone, 

I've been reading a lot about this topic for about a month or so, and still I'm not able to find the answer. I'm an experienced OOP developer and OSINT passionate, so my question is simple. I need a bot/Python script that performs the following action:

INPUT: TgID
Output: phonenumber

I know this is possible by just taking a quick glance at the Telegram API methods, but I've been trying real hard! A Cuban guy could scrape my phone number in seconds (even though my Telegram privacy settings don't allow my phone number to be shared). I've read EVERYTHING, but can't find what I need! Please help me. 
```

**Comment by Bibo-Joshi** [comment]
Hi. this is not a question about any of the functionality of `ptbcontrib` and hence I'll go ahead and close this thread. Besides, I'm rather sure that your question was already answered [in the user group](https://t.me/pythontelegrambotgroup/563863).
