### ISSUE TITLE
[Feature] create chat link for private groups/channels

### ISSUE THREAD

**Issue by Poolitzer** [python-telegram-bot/ptbcontrib#5]
This feature should introduce a `give_me_a_link_to_the_chat_no_matter_what(chat: Chat) -> str` function. This means, it should check if a username exists and then return it like chat.link does. If the chat doesnt have a username and is a group/channel, check if the bot is an admin with add member rights (I think this is required), then check if get_chat returns a link. If not, export a new one. Then return the invite link. And definitely document that calling this might result in three API calls

**Comment by Bibo-Joshi** [comment]
Because this just came up in the off-topic group: A PR may want to allow including the functionality of https://core.telegram.org/bots/api#createchatinvitelink in this.

**Comment by allerter** [comment]
> then check if get_chat returns a link

Why should the bot use `get_chat` when the user already passes the chat to the function?

**Comment by allerter** [comment]
Is it okay to rely on `Chat.bot` being available?

**Comment by Poolitzer** [comment]
Yes
