### ISSUE TITLE
[BUG] postgrespersistence non string keys

### ISSUE THREAD

**Issue by hethon** [python-telegram-bot/ptbcontrib#54]
### Steps to reproduce
1. run this code
```
def set_data(update, context):
    context.user_data["123"] = "string_key"
    context.user_data[123] = "integer_key"

    update.message.reply_text("Data added!")

def get_data(update, context):
    update.message.reply_text(f"user_data: {context.user_data}")

updater = Updater(<TOKEN>, persistence=PostgresPersistence(url=<DB_URL>))
dp = updater.dispatcher
dp.add_handler(CommandHandler('set_data', start))
dp.add_handler(CommandHandler('get_data', get_data))

updater.start_polling()
updater.idle()
```
3. /set_data 
4. press Ctrl+c and re-run your bot
5. /get_data

### The expected response from the bot is...
user_data: {'123': 'string_key', 123: 'integer_key'}

### While the actual response is...
user_data: {'123': 'integer_key'}

I'm using python version 3.10.4, ptb version 13.13

**Comment by Poolitzer** [comment]
Hello there.

Taking from the postgres file, `data [is saved] in JSON format`. JSON does not support non string keys, so the integer gets converted to a string, and overrides the string key.

This module could throw a runtime error at non string keys, but thats not the python way, so I would vote that this is not a bug,
