### ISSUE TITLE
[BUG] Errors in PostgresPersistence data deserialization

### ISSUE THREAD

**Issue by lamu-ai** [python-telegram-bot/ptbcontrib#81]
### Module this issue is about
postgres_persistence

### Steps to reproduce
1. Set application's persistence  using `PostgresPersistence`, using the optional parameter `store_data` with `[bot_data|chat_data|user_data]=False`

2. Start the bot and let it update the data

3. Restart the bot

### MWE

```python
from telegram.ext import ApplicationBuilder, PersistenceInput
from ptbcontrib.postgres_persistence import PostgresPersistence


app = (
    ApplicationBuilder()
    .token("<TOKEN>")
    .persistence(
        PostgresPersistence(
            "<POSTGRES_URI>",
            store_data=PersistenceInput(chat_data=False, bot_data=False, user_data=True, callback_data=True),
        )
    )
    .build()
)

app.run_polling()
```

### Expected behaviour
Bot should restart normally without errors in data deserialization.

### Actual behaviour
Exceptions are raised in DictPersistence, namely
`AttributeError: 'NoneType' object has no attribute 'items'`
that leads to
`TypeError: Unable to deserialize chat_data_json. Not valid JSON`

I think the problem might be the same as [this comment](https://github.com/python-telegram-bot/ptbcontrib/pull/49#issuecomment-1134639985) from PR #49 . I tried to change [these lines](https://github.com/python-telegram-bot/ptbcontrib/blob/main/ptbcontrib/postgres_persistence/postgrespersistence.py#L80-L84) locally
```
--- a/ptbcontrib/postgres_persistence/postgrespersistence.py
+++ b/ptbcontrib/postgres_persistence/postgrespersistence.py
@@ -77,9 +77,9 @@ class PostgresPersistence(DictPersistence):
             data_ = self._session.execute(text("SELECT data FROM persistence")).first()
             data = data_[0] if data_ is not None else {}

-            chat_data_json = data.get("chat_data", "")
-            user_data_json = data.get("user_data", "")
-            bot_data_json = data.get("bot_data", "")
+            chat_data_json = data.get("chat_data", "{}")
+            user_data_json = data.get("user_data", "{}")
+            bot_data_json = data.get("bot_data", "{}")
             conversations_json = data.get("conversations", "{}")
             callback_data_json = data.get("callback_data_json", "")
```
and the bot restarts just fine. I don't know why `callback_data` doesn't have the same problem as the others though.

### Configuration
**Operating System:**
Arch Linux

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 20.3
Bot API 6.7
Python 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
ptbcontrib=0.0.0 (from main branch)
```

**Comment by Bibo-Joshi** [comment]
Thanks for the report @lamu-ai ! Would like like to send a PR with your fix?

**Comment by lamu-ai** [comment]
Sure can! I took a second look at how `callback_data` is loaded and there's nothing trying to access it during deserialization, thus why it causes no errors.

**Comment by Poolitzer** [comment]
We leave issues open until the PR fixing it is merged :)
