### ISSUE TITLE
[BUG] code snippet in roles module doesn't run

### ISSUE THREAD

**Issue by DonutByte** [python-telegram-bot/ptbcontrib#89]
### Module this issue is about
roles

### Steps to reproduce
1. run the script provided in the [README](https://github.com/python-telegram-bot/ptbcontrib/blob/main/ptbcontrib/roles/README.md)

### Expected behaviour
I would expect this code snippet to run a bot

### Actual behaviour
The code throws errors, is incomplete, and misleading
Here are the main issues:
1. [line 67](https://github.com/python-telegram-bot/ptbcontrib/blob/c111451cd93be9481bc82fdf91d1ce6d02662acb/ptbcontrib/roles/README.md?plain=1#L67) forgot to initialize `ApplicationBuilder`. i.e. no parenthesis
2. [line 36](https://github.com/python-telegram-bot/ptbcontrib/blob/c111451cd93be9481bc82fdf91d1ce6d02662acb/ptbcontrib/roles/README.md?plain=1#L36) `roles.add_admin` expects int(s)
3. [lines 62- 65](https://github.com/python-telegram-bot/ptbcontrib/blob/c111451cd93be9481bc82fdf91d1ce6d02662acb/ptbcontrib/roles/README.md?plain=1#L62-L65) `roles.ADMIN` in not defined
4. [line 14](https://github.com/python-telegram-bot/ptbcontrib/blob/c111451cd93be9481bc82fdf91d1ce6d02662acb/ptbcontrib/roles/README.md?plain=1#L14) `CallbackContext` has no attribute 'roles'
5. [line 18](https://github.com/python-telegram-bot/ptbcontrib/blob/c111451cd93be9481bc82fdf91d1ce6d02662acb/ptbcontrib/roles/README.md?plain=1#L18) Same as line 14
6. Didn't start bot by using `application.run_polling()`
7. [line 44](https://github.com/python-telegram-bot/ptbcontrib/blob/c111451cd93be9481bc82fdf91d1ce6d02662acb/ptbcontrib/roles/README.md?plain=1#L44) `Filters` has been changed to `filters` and it's not imported
8. [line 41](https://github.com/python-telegram-bot/ptbcontrib/blob/c111451cd93be9481bc82fdf91d1ce6d02662acb/ptbcontrib/roles/README.md?plain=1#L41) This update blocks any other update, it should be at the bottom
9. [lines 56-56](https://github.com/DonutByte/ptbcontrib/blob/main/ptbcontrib/roles/README.md?plain=1#L56-59) `roles.chat_admins` and `roles.chat_creator` are not defined
10. IMO using `SomeHandler` which isn't an actual python-telegram-bot handler is confusing

### Configuration
**Operating System:**
Any

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 20.3
Bot API 6.7
Python 3.10.5

**Comment by DonutByte** [comment]
there's also a type hint issue in [`RolesHandler.__init__`](https://github.com/python-telegram-bot/ptbcontrib/blob/c111451cd93be9481bc82fdf91d1ce6d02662acb/ptbcontrib/roles/roleshandler.py#L110)
```python
    def __init__(self, handler: BaseHandler[Update, _CCT], roles: Role) -> None:
        self.handler = handler
        self.roles: Union[Role, InvertedRole] = roles
        super().__init__(self.handler.callback)      
```
the `roles` parameter can be either `Role` or `InvertedRole`, as type-hinted 2 lines below (`self.roles: Union[Role, InvertedRole] = roles`)

**Comment by DonutByte** [comment]
@Bibo-Joshi I have just now realized that we forgot to override `check_update` on `InvertedRole`
meaning only message related updates will be handled by it.

It should be an easy fix:
just adding these lines (taken from `Role`) to `InvertedRole`

```py
    def check_update(self, update: Update) -> bool:
        # Override UpdateFilter.check_update to handle also updates that are not messages
        return self.filter(update)
```


P.S.
A developer can `InvertedRole` from their project, while it's not really a problem, but I looked at [another inverted-filter implementation]() which has a `_` prefix.
It's super important, but I thought it might need a 'heads-up'  :)

**Comment by Bibo-Joshi** [comment]
Dedum. Thanks for the finding! I can probably address this on the weekend. If you want to, you can ofc send a PR yourself:)

**Comment by DonutByte** [comment]
I would be happy to do it ;)

Though I'll won't address (unless you think otherwise) the `InvertedRole` prefix, I think it's considered a breaking change.
